N_('Accessibility')
N_('Archiving/Backup')
N_('Archiving/Cd burning')
N_('Archiving/Compression')
N_('Archiving/Other')
N_('Books/Computer books')
N_('Books/Faqs')
N_('Books/Howtos')
N_('Books/Literature')
N_('Books/Other')
N_('Communications')
N_('Databases')
N_('Development/C')
N_('Development/C++')
N_('Development/Databases')
N_('Development/Debug')
N_('Development/Debuggers')
N_('Development/Documentation')
N_('Development/Erlang')
N_('Development/Functional')
N_('Development/GNOME and GTK+')
N_('Development/Haskell')
N_('Development/Java')
N_('Development/KDE and QT')
N_('Development/Kernel')
N_('Development/Lisp')
N_('Development/ML')
N_('Development/Objective-C')
N_('Development/Other')
N_('Development/Perl')
N_('Development/Python')
N_('Development/Python3')
N_('Development/Ruby')
N_('Development/Scheme')
N_('Development/Tcl')
N_('Development/Tools')
N_('Documentation')
N_('Editors')
N_('Education')
N_('Emulators')
N_('Engineering')
N_('File tools')
N_('Games/Adventure')
N_('Games/Arcade')
N_('Games/Boards')
N_('Games/Cards')
N_('Games/Educational')
N_('Games/Other')
N_('Games/Puzzles')
N_('Games/Sports')
N_('Games/Strategy')
N_('Graphical desktop/Enlightenment')
N_('Graphical desktop/FVWM based')
N_('Graphical desktop/GNOME')
N_('Graphical desktop/GNUstep')
N_('Graphical desktop/Icewm')
N_('Graphical desktop/KDE')
N_('Graphical desktop/MATE')
N_('Graphical desktop/Motif')
N_('Graphical desktop/Other')
N_('Graphical desktop/Rox')
N_('Graphical desktop/Sawfish')
N_('Graphical desktop/Sugar')
N_('Graphical desktop/Window Maker')
N_('Graphical desktop/XFce')
N_('Graphics')
N_('Monitoring')
N_('Networking/Chat')
N_('Networking/DNS')
N_('Networking/File transfer')
N_('Networking/FTN')
N_('Networking/IRC')
N_('Networking/Instant messaging')
N_('Networking/Mail')
N_('Networking/News')
N_('Networking/Other')
N_('Networking/Remote access')
N_('Networking/WWW')
N_('Office')
N_('Other')
N_('Publishing')
N_('Sciences/Astronomy')
N_('Sciences/Biology')
N_('Sciences/Chemistry')
N_('Sciences/Computer science')
N_('Sciences/Geosciences')
N_('Sciences/Mathematics')
N_('Sciences/Medicine')
N_('Sciences/Other')
N_('Sciences/Physics')
N_('Security/Antivirus')
N_('Security/Networking')
N_('Shells')
N_('Sound')
N_('System/Base')
N_('System/Configuration/Boot and Init')
N_('System/Configuration/Hardware')
N_('System/Configuration/Networking')
N_('System/Configuration/Other')
N_('System/Configuration/Packaging')
N_('System/Configuration/Printing')
N_('System/Fonts/Console')
N_('System/Fonts/True type')
N_('System/Fonts/Type1')
N_('System/Fonts/X11 bitmap')
N_('System/Internationalization')
N_('System/Kernel and hardware')
N_('System/Libraries')
N_('System/Legacy libraries')
N_('System/Servers')
N_('System/Servers/ZProducts')
N_('System/X11')
N_('System/XFree86')
N_('Terminals')
N_('Text tools')
N_('Toys')
N_('Video')
