
N_('Accessibility')
N_('Adventure')
N_('Antivirus')
N_('Arcade')
N_('Archiving')
N_('Astronomy')
N_('Backup')
N_('Base')
N_('Biology')
N_('Boards')
N_('Books')
N_('Boot and Init')
N_('C')
N_('C++')
N_('Cards')
N_('Cd burning')
N_('Chat')
N_('Chemistry')
N_('Communications')
N_('Compression')
N_('Computer books')
N_('Computer science')
N_('Configuration')
N_('Console')
N_('Databases')
N_('Debug')
N_('Debuggers')
N_('Development')
N_('DNS')
N_('Documentation')
N_('Editors')
N_('Education')
N_('Educational')
N_('Emulators')
N_('Engineering')
N_('Enlightenment')
N_('Erlang')
N_('Faqs')
N_('File tools')
N_('File transfer')
N_('Fonts')
N_('FTN')
N_('Functional')
N_('FVWM based')
N_('Games')
N_('Geosciences')
N_('GNOME')
N_('GNOME and GTK+')
N_('GNUstep')
N_('Graphical desktop')
N_('Graphics')
N_('Hardware')
N_('Haskell')
N_('Howtos')
N_('Icewm')
N_('Instant messaging')
N_('Internationalization')
N_('IRC')
N_('Java')
N_('KDE')
N_('KDE and QT')
N_('Kernel')
N_('Kernel and hardware')
N_('Legacy libraries')
N_('Libraries')
N_('Lisp')
N_('Litterature')
N_('Mail')
N_('MATE')
N_('Mathematics')
N_('Medicine')
N_('ML')
N_('Monitoring')
N_('Motif')
N_('Networking')
N_('News')
N_('Objective-C')
N_('Office')
N_('Other')
N_('Packaging')
N_('Perl')
N_('Physics')
N_('Printing')
N_('Publishing')
N_('Puzzles')
N_('Python')
N_('Python3')
N_('Remote access')
N_('Rox')
N_('Ruby')
N_('Sawfish')
N_('Scheme')
N_('Sciences')
N_('Servers')
N_('Shells')
N_('Sound')
N_('Sports')
N_('Strategy')
N_('Sugar')
N_('System')
N_('Tcl')
N_('Terminals')
N_('Text tools')
N_('Tools')
N_('Toys')
N_('True type')
N_('Type1')
N_('Video')
N_('Window Maker')
N_('WWW')
N_('X11')
N_('X11 bitmap')
N_('XFce')
N_('XFree86')
N_('ZProducts')
